name: flame_spine_example
description: A testbed for flame_spine.
publish_to: 'none'
version: 0.1.0+100

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flame: ^1.0.0
  spine_core: ^0.3.2

  spine_flutter:
    path: ../../spine_flutter
    #git:
    #  url: https://github.com/signmotion/spine_flutter.git
    #  ref: extended_1_simple

  flame_spine:
    path: ../

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/spineboy/
