name: flame_spine_example
description: A testbed for flame_spine.
publish_to: 'none'
version: 0.1.0+100

environment:
  sdk: '>=2.17.3 <3.0.0'
  flutter: '>=3.0.2 <4.0.0'

dependencies:
  flame: ^1.2.0
  spine_core: ^0.3.3

  flame_spine:
    path: ../

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/spineboy/
