name: flame_spine
description: Spine animation support for the Flame game engine. This uses the spine_core and spine_flutter packages and provides wrappers and components to be used inside Flame.
homepage: https://github.com/flame-engine/flame
publish_to: 'none'
version: 0.1.0+100

environment:
  sdk: '>=2.17.3 <3.0.0'
  flutter: '>=3.0.2 <4.0.0'

dependencies:
  flame: 1.2.0
  spine_core: ^0.3.3

  spine_flutter:
    path: ../spine_flutter
    #git:
    #  url: https://github.com/signmotion/spine_flutter.git
    #  ref: extended_1_simple

  flutter:
    sdk: flutter

dev_dependencies:
  dartdoc: ^5.1.2
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.16.0
